### ISSUE TITLE
Incompatible with Kodi 19

### ISSUE THREAD

**Issue by araujorm** [idorel77/CarPc-Carbon-K18#7]
Hi.

Kodi 19 is out, but this skin addon is not compatible. Is there hope that someday we'll see it being ported to Kodi 19?

Thanks and best regards.

**Comment by idorel77** [comment]
Hi ,
try to change gui vers. line 4 : https://github.com/idorel77/CarPc-Carbon-K18/blob/master/addon.xml

From 5.14.0 to 5.15.0 

Hope this work because I don't know if I will continue this ...

**Comment by araujorm** [comment]
Hi.

Thanks. It seems to have worked. Feel free to copy it from here if you want: https://github.com/araujorm/CarPc-Carbon-K19/commit/7211ad8e560e242d234a112eca9d61e6a8f29de4 :)
